### ISSUE TITLE
Weird dark colors on some configs

### ISSUE THREAD

**Issue by HuguesDelorme** [gkv311/occt-samples-qopenglwidget#3]
I built occt-samples-qopenglwidget on two different PCs both running Win10 x64 and got distinct colors brightness.
First PC with OpenGL 4.6:
![image](https://user-images.githubusercontent.com/939132/155616144-cd0130b1-ccb2-45d5-94ce-9ed78848d14a.png)

Second PC with OpenGL 4.3:
![image](https://user-images.githubusercontent.com/939132/155616183-af202cb3-e9d6-4e93-b6a2-8c55cc7ba3bf.png)

What could cause that ?

OpenGL infos dump on second PC:
![image](https://user-images.githubusercontent.com/939132/155616259-017132da-7bb9-46d3-af31-77ca3c35dc3c.png)

On both machines:
Visual C++ 2019
Qt 5.15.2
OpenCascade 7.6.0 from Download center

**Comment by gkv311** [comment]
The second one is incorrect - it handles sRGB OpenGL buffer incorrectly. Cannot say if it is an Intel driver bug or something else (see `aGlFormat.setColorSpace (QSurfaceFormat::sRGBColorSpace); setTextureFormat (GL_SRGB8_ALPHA8);` in the sample code).

If you can launch DRAWEXE.exe on these computers - it would be nice if can check if OCCT Viewer has the same issue without Qt dependency.

**Comment by gkv311** [comment]
> Date: 09/29/2016 | Version: 20.19.15.4531

The Intel driver is more than 5 years old... Though there might be no newer version provided by notebook vendor.

**Comment by HuguesDelorme** [comment]
Here is what's rendered with DRAWEXE on the "second" problematic PC:
```
$> box Shape 100 50 90
$> vdisplay Shape
$> vsetdispmode 1
$> vfit
```
![image](https://user-images.githubusercontent.com/939132/155771876-d7d06ea8-c819-4e64-b77e-8d99f8795b9a.png)

The colors seem correct so the Qt "bridge" might be the cause?

**Comment by HuguesDelorme** [comment]
I've enabled `qt.qpa.gl` logging category with `QT_LOGGING_RULES=qt.qpa.gl=true`
Console output:
```
qt.qpa.gl: QWindowsIntegration::createPlatformOpenGLContext QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.qpa.gl: QWindowsGLContext::QWindowsGLContext WGL extensions: WGL_EXT_depth_float WGL_ARB_buffer_region WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_pixel_format WGL_ARB_pbuffer WGL_EXT_extensions_string WGL_EXT_swap_control WGL_EXT_swap_control_tear WGL_ARB_multisample WGL_ARB_pixel_format_float WGL_ARB_framebuffer_sRGB WGL_ARB_create_context WGL_ARB_create_context_profile WGL_EXT_pixel_format_packed_float WGL_EXT_create_context_es_profile WGL_EXT_create_context_es2_profile WGL_NV_DX_interop WGL_INTEL_cl_sharing WGL_NV_DX_interop2 WGL_ARB_create_context_robustness 
qt.qpa.gl: "ARB::choosePixelFormat  Attributes:  0x2003 , 0x2027 , 0x2010 , 0x1 , 0x2001 , 0x1 , 0x2014 , 0x18 , 0x2011 , 0x1 , 0x2013 , 0x202b , 0x201b , 0x8 , 0x2023 , 0x8 , 0x2041 , 0x0 , \n    obtained px # 5  of  1 \n     PIXELFORMATDESCRIPTOR dwFlags=0x8225 PFD_DRAW_TO_WINDOW PFD_SUPPORT_OPENGL PFD_SUPPORT_COMPOSITION PFD_DOUBLEBUFFER iPixelType=0 cColorBits=32 cRedBits=8 cRedShift=16 cGreenBits=8 cGreenShift=8 cBlueBits=8 cBlueShift=0 cDepthBits=24 cStencilBits=8 iLayerType=0 cAlphaBits=8 cAlphaShift=24 cAccumBits=64 cAccumRedBits=16 cAccumGreenBits=16 cAccumBlueBits=16 cAccumAlphaBits=16 "
qt.qpa.gl: ARB::createContext Creating context version 2 . 0 3 attributes
qt.qpa.gl: QWindowsGLContext::QWindowsGLContext 0x21431f4b9b0 ARB  requested:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
    obtained # 5 ARB QSurfaceFormat(version 4.3, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CompatibilityProfile) 
     PIXELFORMATDESCRIPTOR dwFlags=0x8225 PFD_DRAW_TO_WINDOW PFD_SUPPORT_OPENGL PFD_SUPPORT_COMPOSITION PFD_DOUBLEBUFFER iPixelType=0 cColorBits=32 cRedBits=8 cRedShift=16 cGreenBits=8 cGreenShift=8 cBlueBits=8 cBlueShift=0 cDepthBits=24 cStencilBits=8 iLayerType=0 cAlphaBits=8 cAlphaShift=24 cAccumBits=64 cAccumRedBits=16 cAccumGreenBits=16 cAccumBlueBits=16 cAccumAlphaBits=16  swap interval:  1 
    default:  ContextFormat: v4.3 profile: QSurfaceFormat::CompatibilityProfile options: QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions) 
    HGLRC= 0x10002
```
Is it on any help?

**Comment by HuguesDelorme** [comment]
@gkv311 
I'm having the same color problem on my "Acer Aspire 5" laptop, here are the OpenGL infos :
![image](https://user-images.githubusercontent.com/939132/156899216-ff889b91-63a5-4175-98ba-2a635b40145f.png)
Is there a recurring OpenGL issue with intel graphic chipsets ?

**Comment by gkv311** [comment]
@HuguesDelorme, could you please check if patch pushed to master makes any difference to observed behavior?

**Comment by HuguesDelorme** [comment]
Hello Kirill, sorry for giving you feedback that late.
I've tested your change and it solves the issue on the "second" PC with OpenGL 4.3.0 and also with my laptop PC with OpenGL 4.5.0
👍 

Is there any drawback with your patch we should be aware of ?

**Comment by gkv311** [comment]
Thanks for testing.

> Is there any drawback with your patch we should be aware of ?

Nothing of a great concern but:
- More "magic" code at application level;
- Fallback shading program in OCCT applies an approximated `2.2` gamma correction curve instead of a true [sRGB conversion formula](https://stackoverflow.com/a/61138576/12890689), so that colors will be very close to reference but not exactly equal (e.g. if you'll try to compare background color on screenshot with input values).
