### ISSUE TITLE
Compile error splines

### ISSUE THREAD

**Issue by yvanblanchard** [gkv311/occt-samples-qopenglwidget#6]
@grotius-cnc 
Hello, I tried to compile the occSketcher, but I get compilation issues.
Some are related to opencascade : I am using version 7.6.0, and there are some deprecated classes, but I can deal with it.
But others are related to Spline classes (see image below).
Could you please help me ?
I am using VisualStudio 2017 compiler on WIn10 x64.

![image](https://user-images.githubusercontent.com/63931618/168476192-4a88aadc-eca1-4d4c-9b10-c3d25bacddc7.png)

**Comment by gkv311** [comment]
There is no such code in this repository.
As for the error message - it is illegal in a common C++ to declare C array size from a non-`constexpr` variable. C arrays should be replaced by something else (like `std::array` or `std::vector`)
