### ISSUE TITLE
MacOS Compatibility

### ISSUE THREAD

**Issue by winzlebee** [gkv311/occt-samples-qopenglwidget#7]
Hi @gkv311,

We're looking for any potential pointers for getting this working with MacOS

We maintain a cross-platform application and integrate this component using Qt 5.15.2
We are using OpenCascade 7.6.1

While the component works well on Linux and Windows, on MacOS it seems to have some issues. From the log, the OpenGL context initialises correctly and all FBO creation calls succeed. The off-screen FBO also seems to be drawn to correctly, as `V3d_View::Dump` outputs an image that is correct.

To prevent crashing with a shared OpenGL context on MacOS, as per the Qt Docs, we need to setup the default surface format before `QApplication` is created. MacOS only supports OpenGL 4.1, so the `GL_KHR_DEBUG` extension is not available to us unfortunately.

Currently this results in a black screen, with no useful debug output

Any pointers or clues would be appreciated, or a better method of debugging these graphics issues on MacOS?

**Comment by gkv311** [comment]
> To prevent crashing with a shared OpenGL context on MacOS

I don't get it - does it crash or doesn't draw anything without any message?

**Comment by winzlebee** [comment]
Sorry, I was just referring to the requirement of setting `QSurfaceFormat::setDefaultFormat` At the start, as you have in your latest commit. Without this, we get a crash. 

Once we have it in, we don’t get a crash but instead a black screen. When I have access to the machine again I’ll test your latest changes

**Comment by gkv311** [comment]
You will need the [following OCCT patch](https://tracker.dev.opencascade.org/view.php?id=32991) for running on macOS. I haven't seen any crash though, just a blank viewer.

![Screenshot 2022-05-31 at 07 18 48](https://user-images.githubusercontent.com/851453/171092293-40ba2ef2-1aa6-44f8-b3d7-5b0a55eaff40.png)

**Comment by gkv311** [comment]
It is not the right place to ask about OCCT releases - this is just a small sample project based on OCCT.
