### ISSUE TITLE
layout error when using qt6

### ISSUE THREAD

**Issue by christoffel1989** [gkv311/occt-samples-qopenglwidget#9]
qt6 (button and slider move up)
![image](https://user-images.githubusercontent.com/29227299/194338662-b0ad55b1-bae6-4d4d-a867-0052ea9c2ddf.png)
qt5 (it works correctly)
![image](https://user-images.githubusercontent.com/29227299/194339427-08006cb5-5751-4636-8816-7375d173316d.png)

**Comment by gkv311** [comment]
So far I haven't tried Qt6, so cannot comment what could be the difference in layout. Anyway, I don't think that ui layout is what the sample is supposed to demonstrate ;).
